# FILE: pubmedDB.py
# AUTHOR: Hanie Samimi
# CREATE DATE: 10 April 2020
import pymongo
import re
myclient = pymongo.MongoClient("mongodb://localhost:27017/")

mydb = myclient["pubmedDB"]
mycol = mydb["Article"]
mydict = {"title": "Activity of Ceftolozane/Tazobactam Against Pseudomonas Aeruginosa and Enterobacterales Isolates Recovered From Intensive Care Unit Patients in Spain: The SUPERIOR Multicentre Study", "Abstract":"Patients in intensive care units (ICUs) present a high risk of developing an infection caused by multidrug-resistant bacteria. Consequently, new antimicrobials and combinations are required. In this study, the activity of ceftolozane/tazobactam (C/T) was evaluated against Enterobacterales (n = 400) and Pseudomonas aeruginosa (n = 80) clinical isolates collected from patients in Spanish ICUs with complicated urinary tract infections (cUTI) and complicated intra-abdominal infections (cIAI). Overall susceptibility to C/T in P. aeruginosa isolates by infection type was 95.7% in cUTI (MIC50/90, 1/4 mg/L) and 85.3% in cIAI (MIC50/90, 1/64 mg/L). Activity against P. aeruginosa was maintained regardless of its resistance pattern, confirming that C/T is one of the best antipseudomonal agents along with colistin and amikacin. Susceptibility to C/T in Enterobacterales by infection type was 79.5/81.9% and 89.3/92.3% (EUCAST/CLSI) in cIAI and cUTI isolates, respectively. Activity was excellent against wild-type organisms, with 100% susceptible and inhibited at MIC ≤1 mg/L. Nevertheless, C/T susceptibility decreased against extended-spectrum β-lactamase (ESBL)-producing isolates: Escherichia coli (80.4/84.8% susceptible by EUCAST/CLSI) and Klebsiella pneumoniae (59.1/77.3% susceptible by EUCAST/CLSI). No activity of C/T was observed in carbapenemase-producing isolates. The in vitro activity of C/T observed in this surveillance study suggests that this agent can be considered as a therapeutic option for cUTI and cIAI due to Enterobacterales and P. aeruginosa in ICU patients, particularly when carbapenemase-producing isolates are not involved. ", "meshterms": ["Anti-Bacterial Agents / pharmacology", "Aspartate Aminotransferases / blood", "Cephalosporins / pharmacology *", "Enterobacteriaceae / drug effects *", "Enterobacteriaceae / isolation & purification", "Enterobacteriaceae Infections / microbiology", "Humans", "Intensive Care Units", "Intraabdominal Infections / microbiology", "Microbial Sensitivity Tests", "Prospective Studies", "Pseudomonas Infections / microbiology", "Pseudomonas aeruginosa / drug effects", "Pseudomonas aeruginosa / isolation & purification", "Spain", "Tazobactam / pharmacology", "Urinary Tract Infections / microbiology", "beta-Lactamase Inhibitors / pharmacology" ], "keywords":["Ceftolozane/tazobactam", "Intensive care unit", "Intra-abdominal infection", "Spain","Urinary tract infection"]}
mycol.insert_one(mydict)
term_list = ["developing", "Hanie"]
regexp = re.compile(r"|".join(term_list), re.IGNORECASE)
mydoc = mycol.inventory.find_one({$or: [{"title": regexp },{"Abstract": regexp }]})
